pip install discord.py
pip install asyncio 
pip install json 
pip install random 
pip install discord.ext 
pip install requests 
pip install colorama 
pip install selenium 
pip install time 
pip install pyperclip
pip install requests
pip install selenium
pip install re
pip install subprocess
pip install base64
pip install urllib
pip install datetime
pip install threading
pip install sys
pip install os